"""update default for date_received

Revision ID: 42954935d02e
Revises: 8e4fc1e18ce7
Create Date: 2025-04-20 14:57:57.659775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42954935d02e'
down_revision: Union[str, None] = '8e4fc1e18ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'grades',
        'date_received',
        server_default=sa.func.now
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'grades',
        'date_received',
        server_default=None
    )
    # ### end Alembic commands ###
